### ISSUE TITLE
Usability of torch._index_copy method?

### ISSUE THREAD

**Issue by AlexandrosFerles** [pokaxpoka/deep_Mahalanobis_detector#5]
Dear author, 

may I ask what is the use of the torch idex copy method at the lib_generation.py file in lines 171 to 179?

Thank you in advance.

**Comment by saandeepa93** [comment]
For anyone else wondering the same, its actually channel-wise normalization of gradients to fall in image space. Although I genuinely have no idea why the complicated index_copy_ statements were needed instead of division operation.
